version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: moscow_map_db_service
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-your_db_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your_strong_password}
      POSTGRES_DB: ${POSTGRES_DB:-moscow_map_gisdb}
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-your_db_user} -d ${POSTGRES_DB:-moscow_map_gisdb}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./MosMetroTestTaskServer
      dockerfile: Dockerfile
    container_name: moscow_map_backend_service
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-your_db_user}:${POSTGRES_PASSWORD:-your_strong_password}@db:5432/${POSTGRES_DB:-moscow_map_gisdb}
      PYTHONUNBUFFERED: "1"
    ports:
      - "${BACKEND_HOST_PORT:-8000}:8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./MosMetroFront
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: /api

    container_name: moscow_map_frontend_service
    restart: unless-stopped
    ports:
      - "${FRONTEND_HOST_PORT:-80}:80"
    depends_on:
      - backend

volumes:
  postgres_data_volume:
    driver: local